from crewai import Crew, Process
from agents import blog_researcher, blog_writer
from tasks import research_task, write_task

crew = Crew(
    agents=[blog_researcher, blog_writer],
    tasks=[research_task, write_task],
    process=Process.sequential,
    memory=True,
    cache=True,
    max_rpm=100,
    share_crew=True,
)

try:
    result = crew.kickoff(inputs={'topic': 'AI VS ML VS DL vs Data Science'})
    print(result)
except Exception as e:
    print(f"Crew execution failed: {e}")



# from crewai import Crew, Process  
# # imports Crew (group of agents) and Process (execution strategy)

# from agents import blog_researcher, blog_writer  
# # imports the two agents defined earlier

# from tasks import research_task, write_task  
# # imports the tasks assigned to agents


# # Forming the tech-focused crew with some enhanced configurations

# crew = Crew(
#   agents=[blog_researcher, blog_writer],  
#   # list of agents that will work together in this crew

#   tasks=[research_task, write_task],  
#   # list of tasks to be executed by agents in order

#   process=Process.sequential,  
#   # tasks run one after another (research first, then writing)

#   memory=True,  
#   # enables memory so agents can reuse context between tasks

#   cache=True,  
#   # enables caching to avoid repeating same computations

#   max_rpm=100,  
#   # limits requests per minute (rate control for API usage)

#   share_crew=True  
#   # allows agents to share information within the crew
# )


# ## start the task execution process with enhanced feedback

# result = crew.kickoff(inputs={'topic': 'AI VS ML VS DL vs Data Science'})  
# # starts execution of all tasks with given input topic

# print(result)  
# # prints final output (blog or report generated by crew)